### ISSUE TITLE
Allow user to set env vars from the config options.

### ISSUE THREAD

**Issue by jiegec** [rust-lang/vscode-rust#251]
I am using `Xargo` to cross compile Rust code to aarch64-none-elf with a custom target json. But it seems that `rustc` is called from another directory, so it cannot find it. To allow rustc to find the target spec, I have to use `env RUST_TARGET_PATH=(pwd) code-insiders .`, but I would want this to be configurable in VS Code.

**Comment by nrc** [comment]
More generally, it would be nice to be able to set env vars fir Cargo/rustc from the rls config.
