### ISSUE TITLE
Remove the run|debug tag

### ISSUE THREAD

**Issue by shuaixr** [rust-lang/vscode-rust#795]
When I use rust-analyzer to complete, two tags appear on the function:
![](https://i.loli.net/2020/05/16/CejKUvJzNPnArZ2.png)
They don't work and an error occurs when you click:
![](https://i.loli.net/2020/05/16/ivRm4jl7Gcw8OIg.jpg)
How to remove them？

**Comment by llamicron** [comment]
For anyone looking to hide this: it's `Rust Analyzer > Lens` in VSCode settings.
