### ISSUE TITLE
Cant find crate neon

### ISSUE THREAD

**Issue by Alexander9673** [rust-lang/vscode-rust#810]
Hello, i was wondering everytime i use `use neon;` i keep getting crate not found? But it compiles and runs properly.

**Comment by mcpar-land** [comment]
I'm also experiencing this.

Reproduction steps:

- Install the [Neon](https://github.com/neon-bindings/neon) CLI as per their [getting started tutorial](https://neon-bindings.com/docs/getting-started) (I used yarn, so `yarn global add neon-cli`)
- create a new Neon project
```
neon new neon-bug-test
```
- open the newly-created `./neon-bug-test` in VS Code
- open `native/src/lib.rs`, and note the error at the top of the file:

```
can't find crate for `neon`
```

![image](https://user-images.githubusercontent.com/55669980/87915554-f0315b80-ca37-11ea-8d2a-26b8b64cd2ae.png)

However, running `neon build --release` does **not** give any error messages, and builds without a problem.

**Comment by victorhqc** [comment]
I have the same issue. Interestingly, it only happens in Windows. If I open the exact same project with WSL2 there's no error, same if I try with Mac OSX 😢

**Comment by victorhqc** [comment]
Enabling logs I get the following error
```
{"message":"Neon only builds with --release. For tests, try `cargo test --release`.","code":null,"level":"error","spans":[{"file_name":"C:\\Users\\victo\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\neon-0.4.0\\src\\lib.rs","byte_start":13702,"byte_end":13792,"line_start":356,"line_end":356,"column_start":1,"column_end":91,"is_primary":true,"text":[{"text":"compile_error!(\"Neon only builds with --release. For tests, try `cargo test --release`.\");","highlight_start":1,"highlight_end":91}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[],"rendered":"\u001b[0m\u001b[1m\u001b[38;5;9merror\u001b[0m\u001b[0m\u001b[1m\u001b[38;5;15m: Neon only builds with --release. For tests, try `cargo test --release`.\u001b[0m\n\u001b[0m   \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;14m--> \u001b[0m\u001b[0mC:\\Users\\victo\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\neon-0.4.0\\src\\lib.rs:356:1\u001b[0m\n\u001b[0m    \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;14m|\u001b[0m\n\u001b[0m\u001b[1m\u001b[38;5;14m356\u001b[0m\u001b[0m \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;14m| \u001b[0m\u001b[0mcompile_error!(\"Neon only builds with --release. For tests, try `cargo test --release`.\");\u001b[0m\n\u001b[0m    \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;14m| \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;9m^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\u001b[0m\n\n"}
{"message":"aborting due to previous error","code":null,"level":"error","spans":[],"children":[],"rendered":"\u001b[0m\u001b[1m\u001b[38;5;9merror\u001b[0m\u001b[0m\u001b[1m\u001b[38;5;15m: aborting due to previous error\u001b[0m\n\n"}
```

So maybe it's related on how `neon` asks for release build only. However, why does this happen only on Windows? 🤔

**Comment by lnicola** [comment]
https://github.com/neon-bindings/neon/pull/506/files#diff-b4aea3e418ccdb71239b96952d9cddb6L355

**Comment by victorhqc** [comment]
Ah nice! Thanks for sharing that @lnicola

I replaced my `Cargo.toml` to use latest code from master (maybe this will cause some issues) to

```toml
neon = { git = "https://github.com/neon-bindings/neon.git" }
# neon = "0.4.0"
```

**Comment by Alexander9673** [comment]
it worked as well! i'm going to close this issue now since there is a fix now.
