### ISSUE TITLE
'This app can't run on your PC' when using rust-analyzer

### ISSUE THREAD

**Issue by MarekLg** [rust-lang/vscode-rust#828]
Steps I took:

- installed extension vscode-rust
- installed extension rust-analyzer
- in vscode-rust settings set 'engine' to 'rust-analyzer'
- reload window

Now every time I open vscode this 'This app can't run on your PC' window appears, blocking the window. When I click 'close' to closes, but reopens after a second. I can focus vscode and everything works just fine, but the window remains in the background.

**Comment by lnicola** [comment]
Does a Windows binary downloaded from https://github.com/rust-analyzer/rust-analyzer/releases run for you (once you uncompress it)? If not, can you try installing the Visual C++ 2019 Redistributable from https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads?

**Comment by MarekLg** [comment]
rust-analyzer-windows.exe opens an empty terminal, which closes when I press enter. Is this expected?

**Comment by lnicola** [comment]
Hmm, no, I think it should actually stay open? You can probably check the application loading logs in Event Viewer / Windows Logs / Applications.

Also, does the `matklad.rust-analyzer` extension work for you? The RA support in this one is somewhat experimental.

**Comment by MarekLg** [comment]
The Event viewer doesn't display rust-analyzer.exe when I run it. Disabling this extension resolves the issue. Am I missing out on functionality when I disable vscode-rust?

**Comment by lnicola** [comment]
You miss on being able to switch back to RLS and use the same extension. Today, `matklad.rust-analyzer` has more features and probably works better than this one, but they might get merged in the following weeks or months.

**Comment by MarekLg** [comment]
Good to hear, having everything in one extension sounds neat!
I'll look out for news, then.

Your help was much appreciated, thank you!
