### ISSUE TITLE
Cannot Jump to Defination in Source Code 

### ISSUE THREAD

**Issue by klenkiven** [rust-lang/vscode-rust#834]
When I'm in the souce file, such as `result.rs`.
![image](https://user-images.githubusercontent.com/30347435/89929973-925df100-dc3c-11ea-8c59-d600d7d37c59.png)
![image](https://user-images.githubusercontent.com/30347435/89930045-b6b9cd80-dc3c-11ea-8072-49db8e31ddc3.png)
At 962 line, there is a `Ok()` which i can't use `Ctrl` + Click to defination. And i can't use `right mouse` click find a option that `Go to Defination`.
![image](https://user-images.githubusercontent.com/30347435/89930396-465f7c00-dc3d-11ea-802a-1644e0930685.png)
I only have one way to find its defination by finding its name. 
![image](https://user-images.githubusercontent.com/30347435/89930817-e2898300-dc3d-11ea-9b48-77a186213e00.png)
Although I can find it, it is too complex to find. So I'd like to wish you can fix this bug. (Or add this Feature) to make sure a better use experience.

**Comment by 0xWind** [comment]
I had the same problem, so I'm now using rust-analyzer, which solves my problem!

**Comment by klenkiven** [comment]
> I had the same problem, so I'm now using rust-analyzer, which solves my problem!

Thank you, laotie
