### ISSUE TITLE
[Feature Request] Option to automatically call rustfmt on saving .rs file

### ISSUE THREAD

**Issue by arnabanimesh** [rust-lang/vscode-rust#855]
I really like it when Prettier formats the documents automatically on save. However, since I code mostly in Rust I miss when the code doesn't get formatted automatically on save and I have to call `rustfmt` from the terminal manually.

**Comment by Zageron** [comment]
`.vscode/settings.json`
```json
{
    "editor.formatOnSave": true
}
```

**Comment by arnabanimesh** [comment]
Thanks. At that time it was not working for some reason. Now it is working and I don't know how it got fixed. Closing this issue.
