### ISSUE TITLE
Rust Analyser is starting in a dotnetcore project

### ISSUE THREAD

**Issue by jcbritobr** [rust-lang/vscode-rust#871]
Hello. Rust Analyser thinks csharp projects are rust projects and starts running. Here follow my configuration
rust analyser - v0.2.368
windows 10 64
vscode - 1.50.1

Above are the print of my project
![image](https://user-images.githubusercontent.com/6579862/98232866-f68f0900-1f3c-11eb-9b51-60818f591d80.png)

Couldn't get a trace from the start but it happens only when I start the vscode under desktop shortcut. If I call $ code . in terminal, it doesn't happens.

**Comment by lnicola** [comment]
Which extension are you using? If it's `matklad.rust-analyzer`, you should file this against its repository (https://github.com/rust-analyzer/rust-analyzer/).

**Comment by jcbritobr** [comment]
> 
> 
> Which extension are you using? If it's `matklad.rust-analyzer`, you should file this against its repository (https://github.com/rust-analyzer/rust-analyzer/).

Yep, I have miss the repos. Im sorry.
