### ISSUE TITLE
Rust-Analyzer conflicting ?

### ISSUE THREAD

**Issue by Lukas-Sturm** [rust-lang/vscode-rust#882]
When both this extension and rust-analyzer are installed, a warning is shown that they are known to conflict [#6463](https://github.com/rust-analyzer/rust-analyzer/issues/6463)
But the readme states that either rust-analyzer or the official language server need to be installed. 
This lead to some confusion on my side.

**Comment by lnicola** [comment]
There are two Rust language servers:

 - RLS, the original and official one
 - `rust-analyzer`, an independent implementation that will replace RLS at some undetermined point in the future

You should decide which one to use, then:

 - if you want to use RLS, use `vscode-rust`
 - if you want to use `rust-analyzer`, preferably use `matklad.rust-analyzer`
 - `vscode-rust` has some experimental (and likely outdated) support for `rust-analyzer`, which is what you've seen in the readme; last time someone filed an issue it wasn't working, though

So the `rust-analyzer` warning is correct: you shouldn't install both Code extensions. If you want to use `vscode-rust` with `rust-analyzer`, there's a toggle in the settings.

**Comment by Lukas-Sturm** [comment]
Ah, thanks for the clarification :)
