### ISSUE TITLE
Windows crashes while installing components on WSL

### ISSUE THREAD

**Issue by zrthxn** [rust-lang/vscode-rust#883]
While installing the required components the extension causes Windows 10 to crash to the Blue Screen of Death (BSOD). This doesn't seem to happen on Windows but if I have the workspace open in WSL and then as the extension starts up, one of the installs causes a crash. Windows says KERNEL_SECURITY_CHECK_FAILURE.

**System Information**

VS Code 1.52.1
Rust extension v0.7.8

Windows 10 Build 19041.685
WSL Version 1
WSL OS Ubuntu 18.04

_Crash Message_
**KERNEL_SECURITY_CHECK_FAILURE**

I cannot attach screenshots of the BSOD obviously but I'll try to find which component causes this.

**Comment by lnicola** [comment]
This must be a WSL 1 bug.

**Comment by zrthxn** [comment]
Well if you say so... I don't really know much about how that whole integration works tbh.
I'll close this since in that case you can't really do much I suppose, and if someone else has the issue maybe then we'll look into it.

**Comment by lnicola** [comment]
If a user program crashes Windows, it's a Windows bug.

Just wondering, why aren't you using WSL 2? It's less quirky overall and probably has better performance.

**Comment by zrthxn** [comment]
[WSL 2 is painfully slow](https://github.com/microsoft/WSL/issues/4197) with file IO on drives mounted under `/mnt`. So much so that Webpack's file watcher couldn't even listen for file changes for hot reloading.

And since I use Windows on my desktop and some of my utilities depend on it, I couldn't just start using Linux. So it was either downgrade to WSL 1 or deal with having two copies of my work, one under `/mnt/c/Users` and one under `/home/user`

**Comment by lnicola** [comment]
Yeah, that's a problem. I would either do the two copies thing, or use another solution like the WSL support in Code.

But your workflow is totally valid, of course, and you shouldn't change it if it works for you.
