### ISSUE TITLE
VSCode extension doesn't work when using Rust nightly

### ISSUE THREAD

**Issue by henryboisdequin** [rust-lang/vscode-rust#884]
I'm using Rust nightly to use the Rocket framework. I get the following two errors:

<img width="458" alt="Screenshot 2021-01-12 at 13 41 13" src="https://user-images.githubusercontent.com/65845077/104287027-ddc24700-54db-11eb-8ded-e27b176d2f1a.png">

Is there a way around this?

**Comment by lnicola** [comment]
Run `rustup component add rls`. If it's missing, it didn't build and you can try installing an older nightly. I think you can do that by `rustup toolchain remove nightly; rustup toolchain install nightly --component rls`.

Or you could try `rust-analyzer`: https://marketplace.visualstudio.com/items?itemName=matklad.rust-analyzer.

**Comment by henryboisdequin** [comment]
Thanks this works!
