### ISSUE TITLE
Couldn't start client Rust Language Server

### ISSUE THREAD

**Issue by JerryGreen** [rust-lang/vscode-rust#889]
I use current latest `rust-lang.rust`, v0.7.8 and I have these two errors when starting VSCode:

- "Couldn't start client Rust Language Server"
- "Rustup not available. Install from https://www.rustup.rs/"

![image](https://user-images.githubusercontent.com/13215662/107879576-7abd3900-6efb-11eb-97ff-ce60e8908464.png)

By this reason, "Format on save" feature doesn't work, though manual `cargo fmt` works.

```
cargo --version
cargo 1.50.0 (f04e7fab7 2021-02-04)

rustc --version
rustc 1.50.0 (cb75ad5db 2021-02-10)

rustup --version
rustup 1.23.1 (3df2264a9 2020-11-30)

bash --version
GNU bash, version 4.4.23(1)-release (x86_64-pc-msys)

code --version
1.53.2
622cb03f7e070a9670c94bae1a45d78d7181fbd4
x64
```

I clearly used rustup to install Rust. I also have `~\.cargo\bin` in my `PATH` environment variable. Still, the extension does not work. I suspect it might be something related to Windows things (I pretty much always blame Windows for non-working things 😂), though Rust and VSCode are both multi-OS-friendly, so that's clearly an issue anyway.

**Comment by lnicola** [comment]
Are you starting Code from outside of the terminal? It might be using a different PATH. Even in Linux that's often a problem: people start the editor from their DE, which doesn't source the shell configuration file to set up PATH.

Unrelated, you might want to give rust-analyzer a try (matklad.rust-analyzer on the Marketplace). It's a completely different implementation from RLS, but some people are happy with it.

**Comment by JerryGreen** [comment]
> Are you starting Code from outside of the terminal?
I run `code --version` inside the integrated terminal of VSCode, if that's what your concern. But I just checked that in both native command prompt and powershell, - `cargo`, `rustc`, `rustup` they all work from there. Yet, the extensions somehow tells that `rustup` is not available...

> your mention of `~\.cargo\bin` is a bit strange
Oh, yeah, I'm really sorry for this confusion! In actual `PATH` variable I have a fullpath, but for github I replaced the `C:\Users\Jerry\.cargo\bin` part with `~\.cargo\bin`. Idk why I did that... My bad. It's indeed `C:\Users\Jerry\.cargo\bin`, which is a real path, and has all the executables (`cargo`, `rustc`, `rustup`, etc.)

> you might want to give rust-analyzer a try
Yeah, I tried that. It doesn't give me errors, but it also doesn't seem to have formatter, so it doesn't fit my needs. I'm used to my code being formatted automatically on save, so can't live without it now

**Comment by lnicola** [comment]
> I run code --version inside the integrated terminal of VSCode, if that's what your concern. But I just checked that in both native command prompt and powershell too, - cargo, rustc, rustup they all work from all those shells. Yet, the extension somehow tells that rustup is not available...

I meant starting Code from the Start menu or a shortcut as opposed to a `bash` window. If you start it from a shortcut, it's not going to inherit the `PATH` set in `bash`.

> Yeah, I tried that. It doesn't give me errors, but it also doesn't seem to have formatter, so it doesn't fit my needs. I'm used to my code being formatted automatically on save, so can't live without it now

It runs `cargo check` when saving a file and it certainly has support for auto-formatting, again, only on save. It also has some diagnostics that work on the fly, e.g. for parsing errors. If it doesn't work for you, please file a bug there, but make sure to try that extension, not the support in `rust-lang.rust`.

**Comment by JerryGreen** [comment]
> I meant starting Code from the Start menu or a shortcut as opposed to a bash window. If you start it from a shortcut, it's not going to inherit the PATH set in bash.

Huh, I didn't know that. And answering your question: I start it from a shortcut. But I don't set env variables with bash (like .bashrc or something), instead I set via native "Environment Variables" in System Properties in Control Panel. So I guess it should be visible everywhere, either it's started from bash or a shortcut.

> it certainly has support for auto-formatting

Oh, I just tried it again, and noticed that yes it's actually there and it works (I pretty sure it didn't work last time I tried)! So I guess I'll stick to `matklad.rust-analyzer`, thank you! (Should we close this issue now? 😂 Btw, is `rust-lang.rust` any better than `matklad.rust-analyzer` anyhow? Why it exists?)

**Comment by lnicola** [comment]
> instead I set it via native "Environment Variables" in System Properties

Oh, okay.

> Should we close this issue now?

You could fire up Process Monitor to see what it's trying to run, but you can probably close it since it sounds specific to your setup.

> Why it exists?

It came first and it's (still) the official solution. `rust-analyzer` is supposed to [replace](https://github.com/rust-lang/rfcs/blob/master/text/2912-rust-analyzer.md) it some day.

> is rust-lang.rust any better

Sure, in multiple ways:

 - it gives diagnostics more or less on-the-fly, without having to save the file
 - it's built on the compiler: if some code compiles, RLS won't say it's wrong
 - the inferred types are presumably completely accurate
 - it probably does macro expansion better
 - it's available for more platforms, if you don't want to compile from source
 - it changes less often (some people don't like change)

See https://ferrous-systems.com/blog/rust-analyzer-2019/ for more details.

**Comment by JerryGreen** [comment]
Ok, thank you for all the answers, and patience with my windows-related (probably) problems! Very kind of you. `rust-analyzer` seems good
