### ISSUE TITLE
The Rust Analyzer server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by willparsons** [rust-lang/vscode-rust#890]
When trying to use rust-analyzer as the engine on Windows it seems that the server just keeps crashing and eventually gives up. I have tried looking around for some answers but I haven't come up with anything.

**Comment by lnicola** [comment]
Try the `rust-analyzer` extension from https://marketplace.visualstudio.com/items?itemName=matklad.rust-analyzer. The support in this one is known not to work.

**Comment by willparsons** [comment]
> Try the `rust-analyzer` extension from https://marketplace.visualstudio.com/items?itemName=matklad.rust-analyzer. The support in this one is known not to work.

I've tried this extension as well and it literally doesn't do anything. No completion, no docs, etc.

**Comment by lnicola** [comment]
Please file an issue there if you can, it's supposed to work. Make sure to disable this one first.

**Comment by willparsons** [comment]
Any update on getting rust-analyzer support? Or is it just me?

I've been using the rust-analyzer plugin and it works fine but does seem slower than this plugin.

**Comment by lnicola** [comment]
The rust-analyzer extension is the one supported with rust-analyzer. The integration here is based on an old version of it, and is not maintained. If you found any performance problems with RA, please report them there. They aren't necessarily related to the Code extension.
