### ISSUE TITLE
Rust Debug Watch expressions  uses % as MODULUS not REMAINDER operator

### ISSUE THREAD

**Issue by AdrianJMartin** [rust-lang/vscode-rust#894]
Issue Type: <b>Bug</b>

Not 100% sure this is a bug or a gotcha...

the rust code:

let a = -12 % 5;

a = -2

whilst the debugger watch window

-12 % 5 : 3

Extension version: 0.7.8
VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:31.419Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.68GB (16.71GB free)|
|Process Argv|--crash-reporter-id 65f23d4b-78cc-4b52-aa11-e03c81996842|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30270708
pythontb:30265425
vspre833cf:30267465
vsdfh931:30270786

```

</details>

**Comment by lnicola** [comment]
This is quite surprising, and probably unrelated to the Rust extension. The debugging functionality is provided by an extension, and the debugger is independent of the language. E.g., on Linux:

```
(gdb) p -12 % 5
$1 = -2

(lldb) p -12 % 5
(int) $0 = -2
```

I suspect your debugger (CDB?) takes a different stance on modulo.

**Comment by AdrianJMartin** [comment]
Ah i'm using CodeLLDB for debugging as it has support for Rust...

...and after rtFm ... by default it uses simplified python for watch expressions. It allows native expressions too, but you need to prepend /nat to the expression, and if Rust add the "SourceLanguages":["Rust"] to the launch config:

/se -12 % 5: 3
/py -12 % 5: 3
/nat -12 % 5: -2
