### ISSUE TITLE
VSCode: The Rust Analyzer server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by H36615** [rust-lang/vscode-rust#895]
On Win10, this message pops up as soon as I open rust project in vscode.

- 'Rust' extension installed on vscode, 'rust-analyzer' not installed although it was installed at one point, but uninstalled now.
- Only changed extension setting is rust client engine changed from ```rls``` to ```rust-analyzer```.
- Tried deleting rust-analyzer from %AppData% and reinstalling from vscode prompt.
- VSCode restarted multiple times.
- rls is working ok.

How to fix this?

**Comment by lnicola** [comment]
The `rust-analyzer` integration is currently broken and not really maintained, you should either use RLS or the `rust-analyzer` extension.

**Comment by H36615** [comment]
Ah okay thx for the answer. I wasn't sure if it was working at one point before messing with the extensions.
