### ISSUE TITLE
Not working - error squiggles

### ISSUE THREAD

**Issue by geenva** [rust-lang/vscode-rust#896]
HI Rust! Sorry if this is really common, but the Rust extension isn't working for me.

OS: macOS 11.2.2 - Big Sur
VSCode Version: 1.54.3

I get the Rust bar at the bottom:
![Screenshot](https://mcs.is-inside.me/wL04VjbY.png)
but no error squiggles, even when I do this: 
```rust
const NUMBER: i32 = 3;
fn main() {
    println!("Number {}", NUMBER);
}

println!(ok)
```

As you can see, `ok` is an undefined constant. 

I've tried reinstalling, restarting VSCode and my computer. What else can I do?

**Comment by lnicola** [comment]
`rustlings` has an unusual project structure, see e.g. https://github.com/rust-lang/vscode-rust/issues/835#issuecomment-725426724.

**Comment by geenva** [comment]
AH! I see. Sorry for wasting your time.

**Comment by lnicola** [comment]
Don't worry -- it's arguably a bug, but `rust-analyzer` also doesn't support it AFAIK, so it might be better to fix it in `rustlings` itself.
