### ISSUE TITLE
Remove vscode-Rust from the vs-code marketplace

### ISSUE THREAD

**Issue by branrickman** [rust-lang/vscode-rust#927]
Or at least add text to the extension description pointing people to rust-analyzer.

This project is not currently active, but it still sits on the top of the vscode marketplace. It is tripping up fresh would-be rust programmers (until they happen to hear by word of mouth that rust-analyzer is what they should be using).

Not a dig at anyone, I have huge respect for tool builders, but it is harming the community by adding a [pretty big trap for new users](https://marketplace.visualstudio.com/items?itemName=rust-lang.rust&ssr=false#review-details).

**Comment by computerquip** [comment]
Also just ran into this. In particular, this is still the "recommended" plugin for rust in vs-code.

**Comment by yuhr** [comment]
In my case rust-analyzer extension does not work well (underline warnings & errors don't show up in my code), while this extension just works. Please don't remove.

**Comment by lnicola** [comment]
@yuhr please file a GitHub issue on the `rust-analyzer` repo.

**Comment by yuhr** [comment]
@lnicola But what's the status of this extension? If it's officially in maintenance mode, I'd gladly go for rust-analyzer as you said, but in my case everything's going well with this extension for now.

**Comment by lnicola** [comment]
@yuhr `rust-analyzer` is currently developed independently, but has been accepted as the successor of RLS in https://rust-lang.github.io/rfcs/2912-rust-analyzer.html.

It's less precise than RLS, but arguably more actively maintained and a lot of users are quite happy with it.

**Comment by yuhr** [comment]
@lnicola Thanks for letting me know that. I'll try to take a look into why it doesn't work for my project

**Comment by kkaja123** [comment]
An official extension deprecation feature should be coming in the May 2022 release of VSCode: https://github.com/microsoft/vscode/issues/4772

**Comment by isidorn** [comment]
Hi VS Code PM here 👋 

I just marked the Rust extension as deprecated in favour of the [rust-analyzer one](https://marketplace.visualstudio.com/items?itemName=rust-lang.rust-analyzer)

This should make it clearer for new users. If the extension authors of the old Rust extension do not agree with this please reach out and we can easily change this. Thanks

fyi @lnicola

**Comment by Xanewok** [comment]
No, that's great. Thank you so much for your help!

**Comment by yankeeinlondon** [comment]
I want to remove this extension but the UI offers no option to uninstall. I am using `rust-analyzer` and have for a long while but I'm concerned that this deprecated extension might cause issues and would prefer to just remove it.

**Comment by lnicola** [comment]
@yankeeinlondon I think you can nuke it from `~/.vscode/extensions` (or somewhere under `%APP_DATA%` on Windows).

**Comment by yankeeinlondon** [comment]
Hmmm. I tried to find it with `ls ~/.vscode/extensions | grep rust` and got:

```sh
rust-lang.rust-analyzer-0.3.1229-darwin-x64
rust-lang.rust-analyzer-0.4.1236-darwin-x64
rust-lang.rust-analyzer-0.4.1237-darwin-x64
swellaby.vscode-rust-test-adapter-0.11.0
```

and I believe what i should have seen is `rust-lang.rust` right?

**Comment by lnicola** [comment]
You have the new extension (or three versions of it, some possibly almost empty). I don't see the old extension there. Does it still show up as installed?

**Comment by yankeeinlondon** [comment]
yeah it does but I do see the deprecated notice too:

![image](https://user-images.githubusercontent.com/980757/194931844-5c8945c5-eaa7-4e4f-b62b-4204779fa766.png)

**Comment by yankeeinlondon** [comment]
note: i am using tracing which still needs the nightly analyzer to not produce errors on some of the macros

**Comment by lnicola** [comment]
Yeah, I'm not sure where that extension is coming from. Are you using the sync feature of Code?

Re. nightly, the latest stable RA (from today) is the same as the nightly one. It doesn't matter of your code is using nightly features or not.

**Comment by yankeeinlondon** [comment]
apparently the proc macro which is broken (at least as of yesterday) in RA was fixed several months ago but hadn't made it into the stable release yet so I figured I'd move but I'd prefer to move back to stable when I can. You think today's release get's me there?

WRT to using **sync** ... I am using it.

**Comment by lnicola** [comment]
RA has a stable release every Monday. In addition, it lands in rustup (on the nightly toolchain) every Wednesday or so, where it follows the usual release train and hits stable in up to six weeks. There are no backports.

If you're using the Code extension without an explicit server path, you get the one that's updated weekly. If you use the nightly extension, you get daily updates. The Monday releases are identical to the previous nightlies.

**Comment by yankeeinlondon** [comment]
Ok well that's good to know and makes some sense; i had read that this was fixed months ago on nightly but wasn't sure how it had missed making it to stable. Guess maybe the messenger was wrong about that.

**Comment by lnicola** [comment]
Yeah, "stable" is ambiguous, as it can either be the `rustup` component in the `stable` (which you probably don't want to use with VS Code) or the weekly RA release.

My gut feeling is that your issue is related to the synchronization feature of Code, but I've never used it.
