### ISSUE TITLE
No autocomplete for Rng trait on rand::thread_rng()

### ISSUE THREAD

**Issue by KevinKoetz** [rust-lang/vscode-rust#938]
Trying to follow the [rust-book guide](https://doc.rust-lang.org/book/ch02-00-guessing-game-tutorial.html), i noticed that there is no autocomplete for the [Rng trait](https://docs.rs/rand/latest/rand/trait.Rng.html) on the generator returned by [rand::thread_rng()](https://docs.rs/rand/latest/rand/fn.thread_rng.html).

I get autocompletion for the [RngCore trait](https://docs.rs/rand/latest/rand/trait.RngCore.html), but for none of the other traits.

My code:
```
use rand::Rng;

fn main() {
    let rnd = rand::thread_rng(). //Expecting autocompletion for gen_range() here
    //manually typing "let rnd = rand::thread_rng().gen_range(1..101)" compiles and runs fine.
    println!("rnd: {}", rnd)
}
```

Cargo.toml
```
[package]
name = "guessing_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
```

Installed Version of [rust-lang.rust](https://marketplace.visualstudio.com/items?itemName=rust-lang.rust) vs-code extension: 
0.7.8

rustup component list --installed:
```
cargo-x86_64-pc-windows-msvc
clippy-x86_64-pc-windows-msvc
rls-x86_64-pc-windows-msvc
rust-analysis-x86_64-pc-windows-msvc
rust-docs-x86_64-pc-windows-msvc
rust-src
rust-std-x86_64-pc-windows-msvc
rustc-x86_64-pc-windows-msvc
rustfmt-x86_64-pc-windows-msvc
 ```

**Comment by lnicola** [comment]
I suggest you try https://marketplace.visualstudio.com/items?itemName=matklad.rust-analyzer instead (because of a Code bug you'll get an older version unless you opt in to the pre-release ones). Completion works in this specific case:

![image](https://user-images.githubusercontent.com/308347/150786496-d003ccb9-5b5f-474e-a5b0-c1afb7428d94.png)

CC #927

**Comment by KevinKoetz** [comment]
Thank you very much. Solved the issue.
