### ISSUE TITLE
The extension cannot find the rustup in Debian 11 / Crostini

### ISSUE THREAD

**Issue by cyber9unk** [rust-lang/vscode-rust#942]
**Issues**
Two warnings
- Couldn't  start client Rust Language Server
- Rustup not available. Install from https://rustup.rs

--------
![Screenshot 2022-02-13 06 49 18](https://user-images.githubusercontent.com/92269361/153772023-3b6744d8-2a67-42fa-ba5e-114b721a7eb5.png)

![Screenshot 2022-02-13 22 52 36](https://user-images.githubusercontent.com/92269361/153772245-1ce86f21-1f2f-47ad-b51c-82b36240423c.png)

**When it happens?**
-------
- When opening a rust project.
---
**Expected Action**
- To not get these error messages and start coding normally..
------

**Comments:**
Rust is installed in the machine, the extension simply cannot find it. In the extension settings I manually indicated the path of the files but it's still giving the same errors.
![Screenshot 2022-02-13 22 56 12](https://user-images.githubusercontent.com/92269361/153772355-be41063a-aac9-4b27-9bc2-361bc1f872b0.png)

(Is the path correct? I saw the Rustup file in that folder.)

---------------------
Previously had Crouton / Ubuntu in the same machine and it was pretty straightforward to install and use. Changed back to Crostini (Debian 11) and I could never use Rust since then.

I installed from https://rustup.rs just like the notification told me to do. When it didn't work, I deleted by autouninstall command and installed from here https://www.rust-lang.org/ja/tools/install  
I'm not quite sure about the difference but seems like it's the same file... Anyways, none of these two worked for me.

**Comment by lnicola** [comment]
> (Is the path correct? I saw the Rustup file in that folder.)

No, the path to `rustup` is `~/.cargo/bin/rustup`.

Unrelated, but if you haven't, you might want to give the `rust-analyzer` extension a try, see #927.

**Comment by cyber9unk** [comment]
> 

Thanks! Now it works.
