### ISSUE TITLE
borrow_mut doesnt appear in dropdown list of functions but still works if used

### ISSUE THREAD

**Issue by efthymew** [rust-lang/vscode-rust#950]
![Screenshot 2022-04-13 171603](https://user-images.githubusercontent.com/46240477/163271767-68dcb87e-2083-409c-90ec-1ac7bf15d0db.png)

borrow_mut doesnt appear in autofill function list, but if i use the function the documentation appears and the code compiles -- am i missing something and this is intended?

**Comment by lnicola** [comment]
> am i missing something

Yes, https://marketplace.visualstudio.com/items?itemName=matklad.rust-analyzer:

![image](https://user-images.githubusercontent.com/308347/163324000-f4ea5964-0513-4900-afcc-8d7f8d34f7f3.png)

**Comment by efthymew** [comment]
Ayyy thanks man! I had no idea there was another rust extension

**Comment by lnicola** [comment]
Yup, see https://blog.rust-lang.org/2022/02/21/rust-analyzer-joins-rust-org.html.
