### ISSUE TITLE
Outline view Follow Cursor does not work

### ISSUE THREAD

**Issue by ljhm** [rust-lang/vscode-rust#951]
macOS: 12.3.1
VSCode: 1.66.2
rust-lang.rust: v0.7.8

Outline view `Follow Cursor` does not work. The corresponding function name entries in outline view will not highlight  when clicking between function bodies.

**Comment by lnicola** [comment]
You should give https://marketplace.visualstudio.com/items?itemName=matklad.rust-analyzer a try.

**Comment by ljhm** [comment]
`rust-lang.rust` already provides outline view. clicking function name entry will show the corresponding function body.

It is just the reverse does not work, clicking inside function body does not show the function name entry. Will `rust-lang.rust` not include this feature in the future? I prefer not installing too many extra extensions on VSCode.

**Comment by lnicola** [comment]
`rust-lang.rust` has been unmaintained for more than a year and is going to be replaced with `rust-analyzer`: https://blog.rust-lang.org/2022/02/21/rust-analyzer-joins-rust-org.html, https://github.com/rust-lang/vscode-rust/issues/927 etc.

**Comment by ljhm** [comment]
Thanks, I just uninstall rust-lang.rust and install matklad.rust-analyzer. rust-analyzer seems cool. rename by F2 works too.
