### ISSUE TITLE
Unit test button runs all tests

### ISSUE THREAD

**Issue by cong-or** [rust-lang/vscode-rust#954]
After migrating from the old `rust analyzer` extension to the new shiny one [official rust lang](https://github.com/rust-lang/vscode-rust/issues/812) . I have noticed that clicking on a single unit tests  runs all of the unit tests within the child and parent directories. 

Is this expected? Or a config issue on my side? 

Thanks

**Comment by lnicola** [comment]
You've got these wrong. `rust-analyzer` is the new extension, recently renamed to `rust-lang.rust-analyzer`. `rust-lang.rust` (the one in this repo) is unmaintained.
