### ISSUE TITLE
missing field `position_encoding` in initializer of `ServerCapabilities`

### ISSUE THREAD

**Issue by alessandro-baldassarre** [rust-lang/vscode-rust#965]
error during installation of cargo modules:

error[E0063]: missing field `position_encoding` in initializer of `ServerCapabilities`

/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_rust-analyzer-0.0.134/src/caps.rs:21:5

**Comment by lnicola** [comment]
Adding a dependency to `lsp-types = "=0.93.1"` might fix that, but what exactly are you trying to do?

**Comment by alessandro-baldassarre** [comment]
sorry, my bad. I open an issue in the right place
