### ISSUE TITLE
Please return RLS server

### ISSUE THREAD

**Issue by Mingun** [rust-lang/vscode-rust#968]
rust-analyzer is still in unusable state in comparing to RLS, please rollback replacing RLS with dummy server!

**Comment by lnicola** [comment]
Did you file any rust-analyzer issue for your problems?

**Comment by Mingun** [comment]
Not yet. But I cannot wait while those problems will be fixed -- these problems were the same a year ago

**Comment by lnicola** [comment]
Have those problems been reported? Do you mean on-the-fly diagnostics?

RLS won't be coming back, it's not longer maintained. rust-analyzer is at least better than one year ago.

**Comment by Mingun** [comment]
Reported: https://github.com/rust-lang/rust-analyzer/issues/13551

RLS worked yesterday, until I upgrade VSCode to 1.73.0. What's changed that it is no longer worked?

> RLS won't be coming back, it's not longer maintained

I'm not asking to maintain it, but why it was necessary to break what worked? Why to remove working implementation and replace it with dummy code?

**Comment by lnicola** [comment]
> RLS worked yesterday, until I upgrade VSCode to 1.73.0. What's changed that it is no longer worked?

RLS was replaced with a stub implementation that shows a warning message. The deprecation was announced in https://blog.rust-lang.org/2022/07/01/RLS-deprecation.html.

> I'm not asking to maintain it, but why it was necessary to break what worked?

RLS depended on compiler implementation details and while I haven't worked on it, it seemed to me that it needed a considerable amount of effort to keep up to date. I remember when it didn't build for weeks at a time.

**Comment by Mingun** [comment]
Thanks for your support. Ok, at least for now go to declaration in rust-analyzer start working, that is enougth

**Comment by lnicola** [comment]
I hope every feature is working in that project, not just Go to declaration. If you find that something is missing (except on-the-fly diagnostics (*) and single-file support), feel free to file new issues.

(*) we do have those, kind of, but they're somewhat hidden
